import img1 from '../../assets/img/Rectangle 5.svg'
import img2 from '../../assets/img/Rectangle 6.svg'
import img3 from '../../assets/img/Rectangle 7.svg'
import img4 from '../../assets/img/Rectangle 8.svg'
import img5 from '../../assets/img/Rectangle 9.svg'
import img6 from '../../assets/img/Rectangle 10.svg'
import img7 from '../../assets/img/Rectangle 11.svg'
import img8 from '../../assets/img/Rectangle 12.svg'
import img9 from '../../assets/img/Rectangle 13.svg'
import img10 from '../../assets/img/Rectangle 14.svg'
import img11 from '../../assets/img/Rectangle 15.svg'


export const Array = [
    {
        id: "1",
        date: '04.02.2023',
        photo: img1,
        title: "Нафтопереробний комплекс для зберігання та переробки нафтопродуктів (Західна Україна)",
        price: "3 500 000",
        selected: 0,
        views: 0,
    },
    {
        id: "2",
        date: '04.02.2023',
        photo: img2,
        title: "Продаж готелю «Синевірський перевал» на Закарпатті",
        price: "750 000",
        selected: 0,
        views: 0,
    },
    {
        id: "3",
        date: '04.02.2023',
        photo: img3,
        title: "Туристичний комплекс 'Форель' під реконструкцію / редевелопмент у Закарпатті",
        price: "380 000",
        selected: 0,
        views: 0,
    },
    {
        id: "4",
        date: '22.01.2023',
        photo: img4,
        title: "Продаж ділянки промислового призначення 4,8 Га у смт Вороновиця (20 км. від Вінниці)",
        price: "200 000",
        selected: 0,
        views: 0,
    },
    {
        id: "5",
        date: '04.01.2023',
        photo: img5,
        title: "ФУЛФІЛМЕНТ - аутсорсинг послуг складської логістики",
        price: "220 000",
        selected: 0,
        views: 0,
    },
    {
        id: "6",
        date: '02.01.2023',
        photo: img6,
        title: "Butlers - мережа магазинів товарів та декору для дому",
        price: "1 280 000",
        selected: 0,
        views: 0,
    },
    {
        id: "7",
        date: '12.01.2023',
        photo: img7,
        title: "Продаж багатопрофільного медичного центру",
        price: "8 500 000",
        selected: 0,
        views: 0,
    },
    {
        id: "8",
        date: '11.01.2023',
        photo: img8,
        title: "Продаж майнового комплексу (2,7 га та 8 200 кв.м. адміністративно-промислових споруд) у Києві",
        price: "3 000 000",
        selected: 0,
        views: 0,
    },
    {
        id: "9",
        date: '02.01.2023',
        photo: img9,
        title: "Проект розширення санаторно-курортного комплексу у Закарпатській області",
        price: "4 550 000",
        selected: 0,
        views: 0,
    },
    {
        id: "10",
        date: '12.01.2023',
        photo: img10,
        title: "Продаж виробничого комплексу з житловою інфраструктурою в Естонії",
        price: "1 500 000",
    },
    {
        id: "11",
        date: '02.01.2023',
        photo: img11,
        title: "Україна отримає перший €1 млрд від ЄС на відновлення після війни",
        price: "3 550 000",
    },
    {
        id: "12",
        date: '04.02.2023',
        photo: img1,
        title: "Нафтопереробний комплекс для зберігання та переробки нафтопродуктів (Західна Україна)",
        price: "3 500 000",
        selected: 0,
        views: 0,
    },
    {
        id: "13",
        date: '04.02.2023',
        photo: img2,
        title: "Продаж готелю «Синевірський перевал» на Закарпатті",
        price: "750 000",
        selected: 0,
        views: 0,
    },
    {
        id: "14",
        date: '04.02.2023',
        photo: img3,
        title: "Туристичний комплекс 'Форель' під реконструкцію / редевелопмент у Закарпатті",
        price: "380 000",
        selected: 0,
        views: 0,
    },
    {
        id: "15",
        date: '22.01.2023',
        photo: img4,
        title: "Продаж ділянки промислового призначення 4,8 Га у смт Вороновиця (20 км. від Вінниці)",
        price: "200 000",
        selected: 0,
        views: 0,
    },
    {
        id: "16",
        date: '04.01.2023',
        photo: img5,
        title: "ФУЛФІЛМЕНТ - аутсорсинг послуг складської логістики",
        price: "220 000",
        selected: 0,
        views: 0,
    },
    {
        id: "17",
        date: '02.01.2023',
        photo: img6,
        title: "Butlers - мережа магазинів товарів та декору для дому",
        price: "1 280 000",
        selected: 0,
        views: 0,
    },
    {
        id: "18",
        date: '12.01.2023',
        photo: img7,
        title: "Продаж багатопрофільного медичного центру",
        price: "8 500 000",
        selected: 0,
        views: 0,
    },
    {
        id: "19",
        date: '11.01.2023',
        photo: img8,
        title: "Продаж майнового комплексу (2,7 га та 8 200 кв.м. адміністративно-промислових споруд) у Києві",
        price: "3 000 000",
        selected: 0,
        views: 0,
    },
    {
        id: "20",
        date: '02.01.2023',
        photo: img9,
        title: "Проект розширення санаторно-курортного комплексу у Закарпатській області",
        price: "4 550 000",
        selected: 0,
        views: 0,
    },
    {
        id: "21",
        date: '12.01.2023',
        photo: img10,
        title: "Продаж виробничого комплексу з житловою інфраструктурою в Естонії",
        price: "1 500 000",
    },
    {
        id: "22",
        date: '02.01.2023',
        photo: img11,
        title: "Україна отримає перший €1 млрд від ЄС на відновлення після війни",
        price: "3 550 000",
    },
    {
        id: "23",
        date: '04.02.2023',
        photo: img1,
        title: "Нафтопереробний комплекс для зберігання та переробки нафтопродуктів (Західна Україна)",
        price: "3 500 000",
        selected: 0,
        views: 0,
    },
    {
        id: "24",
        date: '04.02.2023',
        photo: img2,
        title: "Продаж готелю «Синевірський перевал» на Закарпатті",
        price: "750 000",
        selected: 0,
        views: 0,
    },
    {
        id: "25",
        date: '04.02.2023',
        photo: img3,
        title: "Туристичний комплекс 'Форель' під реконструкцію / редевелопмент у Закарпатті",
        price: "380 000",
        selected: 0,
        views: 0,
    },
    {
        id: "26",
        date: '22.01.2023',
        photo: img4,
        title: "Продаж ділянки промислового призначення 4,8 Га у смт Вороновиця (20 км. від Вінниці)",
        price: "200 000",
        selected: 0,
        views: 0,
    },
    {
        id: "27",
        date: '04.01.2023',
        photo: img5,
        title: "ФУЛФІЛМЕНТ - аутсорсинг послуг складської логістики",
        price: "220 000",
        selected: 0,
        views: 0,
    },
    {
        id: "28",
        date: '02.01.2023',
        photo: img6,
        title: "Butlers - мережа магазинів товарів та декору для дому",
        price: "1 280 000",
        selected: 0,
        views: 0,
    },
    {
        id: "29",
        date: '12.01.2023',
        photo: img7,
        title: "Продаж багатопрофільного медичного центру",
        price: "8 500 000",
        selected: 0,
        views: 0,
    },
    {
        id: "30",
        date: '11.01.2023',
        photo: img8,
        title: "Продаж майнового комплексу (2,7 га та 8 200 кв.м. адміністративно-промислових споруд) у Києві",
        price: "3 000 000",
        selected: 0,
        views: 0,
    },
    {
        id: "31",
        date: '02.01.2023',
        photo: img9,
        title: "Проект розширення санаторно-курортного комплексу у Закарпатській області",
        price: "4 550 000",
        selected: 0,
        views: 0,
    },
    {
        id: "32",
        date: '21.11.2020',
        photo: img10,
        title: "Продаж виробничого комплексу з житловою інфраструктурою в Естонії",
        price: "500 000",
    },
    {
        id: "33",
        date: '12.04.2021',
        photo: img11,
        title: "Перший €1 млрд від ЄС на відновлення після війни",
        price: "2 550 000",
    },
    {
        id: "34",
        date: '12.04.2021',
        photo: img1,
        title: "Перший €1 млрд від ЄС на відновлення після війни",
        price: "2 550 000",
        selected: 0,
        views: 0,
    },
]
